Repository linkerd/linkerd, pull requests merged in 2018-02, with the labels that each got.

#1774 Use a single client for the entire k8s namer
  namer/k8s/src/main/scala/io/buoyant/namer/k8s/K8sInitializer.scala
Labels: review

#1814 Update h2 docs to reflect current implementation
  linkerd/docs/interpreter.md
  linkerd/docs/protocol-h2.md
  linkerd/docs/protocol-http.md
Labels: review

#1813 add GOVERNANCE.md and denote super-maintainers
  GOVERNANCE.md
  MAINTAINERS.md
Labels: review

#1815 add @Ashald to MAINTAINERS.md
  MAINTAINERS.md
Labels: review

#1816 Filter out dirs when listing namespaces in Consul
  namerd/storage/consul/src/main/scala/io/buoyant/namerd/storage/consul/ConsulDtabStore.scala
  namerd/storage/consul/src/test/scala/io/buoyant/namerd/storage/consul/ConsulDtabStoreTest.scala
Labels: review

#1819 add @zackangelo to MAINTAINERS.md
  MAINTAINERS.md
Labels: review

#1828 Fix potential race condition in ExistentialStability
  finagle/buoyant/src/main/scala/com/twitter/finagle/buoyant/ExistentialStability.scala
Labels: bug, kubernetes, review

#1810 Fix issue where k8s ingresses are sometimes not deleted
  k8s/src/main/scala/io/buoyant/k8s/Watchable.scala
  k8s/src/test/scala/io/buoyant/k8s/v1/ApiTest.scala
Labels: reviewable

#1830 Fix ZooKeeper session management
  linkerd/tls/src/main/scala/io/buoyant/linkerd/tls/TlsUtils.scala
  namerd/docs/interface.md
  namerd/iface/interpreter-thrift-idl/src/main/thrift/namer.thrift
  namerd/iface/interpreter-thrift/src/main/scala/io/buoyant/namerd/iface/ThriftInterpreterInterfaceConfig.scala
  namerd/iface/interpreter-thrift/src/main/scala/io/buoyant/namerd/iface/ThriftNamerClient.scala
  namerd/iface/interpreter-thrift/src/main/scala/io/buoyant/namerd/iface/ThriftNamerInterface.scala
  namerd/iface/interpreter-thrift/src/test/scala/io/buoyant/namerd/iface/ThriftNamerEndToEndTest.scala
  namerd/iface/interpreter-thrift/src/test/scala/io/buoyant/namerd/iface/ThriftNamerInterfaceTest.scala
  namerd/storage/zk/src/main/scala/com/twitter/finagle/serverset2/buoyant/ZkDtabStore.scala
  namerd/storage/zk/src/main/scala/com/twitter/finagle/serverset2/buoyant/ZkSession.scala
Labels: review
